#!/bin/sh

mkdir -p opk
cp ./sdlgnuboy.dge opk/sdlgnuboy.dge
cp ./icon.png opk/icon.png
cp ./COPYING opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=GnuBoy
Comment=Game boy emulator
Exec=sdlgnuboy.dge %f rs90
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default.rs90.desktop

print '[Desktop Entry]
Type=Application
Name=GnuBoy
Comment=Game boy emulator
Exec=sdlgnuboy.dge %f rg99
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default.rg99.desktop

mksquashfs ./opk gnuboy_rs90.opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
